name: JSON Server CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: |
        npm install
    
    - name: Start JSON Server
      run: |
        cd server
        npx json-server --watch db.json --routes routes.json --port $PORT
      env:
        PORT: 3000
    
    - name: Install ngrok
      run: npm install -g ngrok
    
    - name: Start ngrok
      run: |
        ngrok http 3000 > /dev/null &
        sleep 5 # Give ngrok some time to initialize
    
    - name: Display ngrok URL
      run: curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
